export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES"
export const FETCH_LATEST_MOVIES = "FETCH_LATEST_MOVIES"
export const FETCH_TRENDING_MOVIES_BY_DAY = "FETCH_TRENDING_MOVIES_BY_DAY"
export const FETCH_TRENDING_MOVIES_BY_WEEK = "FETCH_TRENDING_MOVIES_BY_WEEK"
export const FETCH_NOW_PLAYING_MOVIES = "FETCH_NOW_PLAYING_MOVIES"
export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES"
export const FETCH_TOP_RATED_MOVIES = "FETCH_TOP_RATED_MOVIES"

export const FETCH_POPULAR_TV_SHOWS = "FETCH_POPULAR_TV_SHOWS"
export const FETCH_AIRING_TODAY_TV_SHOWS = "FETCH_AIRING_TODAY_TV_SHOWS"
export const FETCH_ON_THE_AIR_TV_SHOWS = "FETCH_ON_THE_AIR_TV_SHOWS"
export const FETCH_TOP_RATED_TV_SHOWS = "FETCH_TOP_RATED_TV_SHOWS"

export const FETCH_POPULAR_PEOPLE = "FETCH_POPULAR_PEOPLE"

export const NEXT_FORM = "NEXT_FORM"
export const PREV_FORM = "PREV_FORM"